language: none

branches:
  only:
    - master

build:
  ci:
    - git remote set-url origin git@github.com:justin8/abachi-proxy-config.git
    # Update raspberry-pi2 branch
    - git checkout raspberry-pi2
    - git rebase origin/master
    - GIT_SSH_COMMAND="ssh -i /tmp/ssh/shippableabachiproxyconfigdeploykey" git push -f

integrations:
  key:
    - integrationName: shippable-abachi-proxy-config-deploy-key
      type: ssh-key
