version: "2"

services:
    nginx:
        image: justin8/simple-proxy:armhf
        network_mode: bridge
        environment:
          - "DNS_TLD=dray.id.au"
          - "VIRTUAL_PORT=8000"
          - "VIRTUAL_HOST=hass.dray.id.au,backups.dray.id.au,grafana.dray.id.au,node-red.dray.id.au"
          - "LETSENCRYPT_HOST=hass.dray.id.au,backups.dray.id.au,grafana.dray.id.au,node-red.dray.id.au"
          - "LETSENCRYPT_EMAIL=abachi+proxy-config@dray.id.au"
        volumes:
          - ./nginx-config.yml:/config.yml:ro
        ports:
          - "8000:8000"
